Don't override element property value with initial value
vaadin/vaadin-rich-text-editor-flow pull request #110
Opened 2020-09-22 10:25 UTC by denis-anisimov

Fixes #109

2020-09-22 10:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/vaadin-rich-text-editor-flow?pullRequest=110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/vaadin-rich-text-editor-flow?pullRequest=110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/vaadin-rich-text-editor-flow?pullRequest=110) it.</sub>

2020-09-25 14:26 UTC, mshabarov requested changes

2020-09-28 07:33 UTC, denis-anisimov commented on vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java
> +     * arguments. If {@code isInitialValueOptional} is {@code true} then the
Removed

2020-09-28 11:12 UTC, mshabarov approved these changes

2020-09-28 11:12 UTC, merged